# Generated by Django 2.2 on 2019-05-03 11:18

import BaseApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckingStatuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Duties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=250)),
                ('Content', models.TextField()),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('DeadLineDate', models.DateField()),
                ('CheckStatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseApp.CheckingStatuses')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MemberGenderTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MemberPositionTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MemberStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Priorities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMembersTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=200)),
                ('Lname', models.CharField(max_length=250)),
                ('MobileNumber', models.CharField(max_length=11)),
                ('MemberNationalCode', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=250)),
                ('Image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics')),
                ('FamilyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseApp.FamilyTbl')),
                ('Gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseApp.MemberGenderTbl')),
                ('IsActive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseApp.MemberStatus')),
                ('MemberPositionID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseApp.MemberPositionTbl')),
                ('UserMember', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DutyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images', models.ImageField(upload_to=BaseApp.models.get_upload_path)),
                ('DutyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseApp.Duties')),
            ],
        ),
        migrations.AddField(
            model_name='duties',
            name='DutyReceiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Duty_Receiver_Relation', to='BaseApp.FamilyMembersTbl'),
        ),
        migrations.AddField(
            model_name='duties',
            name='DutySender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Duty_Sender_Relation', to='BaseApp.FamilyMembersTbl'),
        ),
        migrations.AddField(
            model_name='duties',
            name='Priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseApp.Priorities'),
        ),
    ]
