# Generated by Django 2.2 on 2019-05-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familytbl',
            name='FamilyCode',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
