# Generated by Django 2.2 on 2019-06-19 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0002_familytbl_familycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymemberstbl',
            name='FamilyID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BaseApp.FamilyTbl'),
        ),
        migrations.AlterField(
            model_name='familymemberstbl',
            name='IsActive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseApp.MemberStatus'),
        ),
        migrations.AlterField(
            model_name='familymemberstbl',
            name='UserMember',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
