# Generated by Django 2.2 on 2019-06-23 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0003_auto_20190619_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymemberstbl',
            name='IsActive',
            field=models.ForeignKey(blank=True, default=2, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseApp.MemberStatus'),
        ),
    ]
