# Generated by Django 2.2 on 2019-08-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0004_auto_20190623_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duties',
            name='DeadLineDate',
            field=models.DateTimeField(),
        ),
    ]
